### ISSUE TITLE
Add configuration via .noterc file.

### ISSUE THREAD

**Issue by dcchambers** [dcchambers/note-keeper#1]
Allow a user to specify configuration in a .noterc file.
* /path/to/notes/
* Default Editor

**Comment by dcchambers** [comment]
As of v0.3.0 it now uses the $EDITOR environment variable as the default editor for opening notes. I suppose some people might want to use a different editor for this than their default, so possibly still worth implementing.

**Comment by jonathandion** [comment]
`~/.config/note/noterc`
