### ISSUE TITLE
Multiple notes for a single day

### ISSUE THREAD

**Issue by luthes** [dcchambers/note-keeper#12]
It'd be nice to have multiple notes for a day. Edit: Flag for --new, --title, or something similar.

Also, sorry for all the issues :) I did something similar a while ago when I was looking for a way to create notes. For all of those that I created, I'll work on implementing and make a pull request. Shouldn't take but a few hours.

**Comment by dcchambers** [comment]
No worries at all! Thanks for the feedback and suggestions. "Definitely* feel free to to fork and submit a PR if you want to!

**Comment by jonathandion** [comment]
I would like to use the same note sometime too.

**Comment by dcchambers** [comment]
This is implemented with v0.4 and above. You can now create a named note with the `-n` flag.
e.g `note -n mynote.md`
