### ISSUE TITLE
Add note-keeper to package managers

### ISSUE THREAD

**Issue by jonathandion** [dcchambers/note-keeper#14]
Are we considering to add `note-keeper` to AUR, brew etc?

**Comment by dcchambers** [comment]
I will create a homebrew tap here: https://github.com/dcchambers/homebrew-tap but could use help porting it to other package managers (eg AUR) if people want.

**Comment by dcchambers** [comment]
You can now install notekeeper with homebrew!

[Formula](https://github.com/dcchambers/homebrew-tap/blob/master/Formula/notekeeper.rb)
```
brew tap dcchambers/tap
brew update && brew install notekeeper
```
