### ISSUE TITLE
forked it

### ISSUE THREAD

**Issue by sandylaw** [dcchambers/note-keeper#29]
https://github.com/sandylaw/notes/blob/main/note
Thank you.

add:

- 1.  -c | --category                     Set category for note.
- 2. -m | --menu                         Update README and /index.md
- 3.  -g | --gitpush                      Push to github

**Comment by dcchambers** [comment]
Hi @sandylaw - I've changed quite a bit of the code lately, but feel free to update your fork and open a pull request if you'd like to merge your changes in!

Cheers
