### ISSUE TITLE
Add ability to destroy a note.

### ISSUE THREAD

**Issue by dcchambers** [dcchambers/note-keeper#5]
Maybe with -d | --destroy | --delete flag.

**Comment by luthes** [comment]
Just a personal preference, but it might be nice to drop it into a trash folder within the notes directory for delete, destroy could permanently delete?

**Comment by dcchambers** [comment]
That's a great idea. Thanks for the suggestion!

**Comment by dcchambers** [comment]
How about `$ note -d | --delete` to move a note to ~/notes/trash/ (where they remain indefinitely)
but `$ note -dy | --destroy` to permanently destroy a note (with a user confirmation prompt).

**Comment by dcchambers** [comment]
`$ note -ds` might make more sense. Easier to type since the `d` and `s` are right next to eachother.
...and `-dsf` to force destroy a note (no Y/N prompt).
